# Generated by Django 2.2.26 on 2022-07-05 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20220705_0604'),
        ('auth', '0011_update_proxy_permissions'),
        ('website', '0002_auto_20220705_0604'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User1',
            new_name='User',
        ),
    ]
