# Generated by Django 2.2.26 on 2022-07-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20220719_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver_name',
            field=models.CharField(default='LockeI', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(default='LockeI', max_length=150),
            preserve_default=False,
        ),
    ]
