# Generated by Django 2.2.26 on 2022-07-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_user_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('member_amount', models.IntegerField(default=1)),
                ('members', models.TextField()),
            ],
        ),
    ]
